# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todo_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 528)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addItem_lineEdit = QtWidgets.QListView(self.centralwidget,)
        self.addItem_lineEdit.setGeometry(QtCore.QRect(60, 30, 421, 81))
        self.addItem_lineEdit.setObjectName("addItem_lineEdit")
        self.mylist_listWidget = QtWidgets.QListView(self.centralwidget)
        self.mylist_listWidget.setGeometry(QtCore.QRect(60, 180, 421, 192))
        self.mylist_listWidget.setObjectName("mylist_listWidget")
        self.add_item_pushbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.add_it())
        self.add_item_pushbutton.setGeometry(QtCore.QRect(60, 130, 131, 28))
        self.add_item_pushbutton.setObjectName("add_item_pushbutton")
        self.delete_item_pushbuuton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.delete_it())

        self.delete_item_pushbuuton.setGeometry(QtCore.QRect(210, 130, 141, 28))
        self.delete_item_pushbuuton.setObjectName("delete_item_pushbuuton")
        self.clear_item_pushbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.clear_it())


        self.clear_item_pushbutton.setGeometry(QtCore.QRect(370, 130, 93, 28))
        self.clear_item_pushbutton.setObjectName("clear_item_pushbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 517, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)




    def add_it(self):
        #Grab the item from the list ...



        item = self.addItem_lineEdit.text()


        self.mylist_listWidget.addItem(item)

        self.addItem_lineEdit.setText("")




    

      

      

      


    

    def delete_it(self):
         pass
         




         def clear_it(self):
             pass





      




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_item_pushbutton.setText(_translate("MainWindow", "Add Item to a list "))
        self.delete_item_pushbuuton.setText(_translate("MainWindow", "Delete Item to a list"))
        self.clear_item_pushbutton.setText(_translate("MainWindow", "Clear List"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
