# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 717)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(34)
        self.output_label.setFont(font)
        self.output_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_label.setObjectName("output_label")
        self.remainder_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("%"))
        self.remainder_button.setGeometry(QtCore.QRect(0, 100, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.remainder_button.setFont(font)
        self.remainder_button.setObjectName("remainder_button")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("C"))
        self.clear_button.setGeometry(QtCore.QRect(90, 100, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.clear_button.setFont(font)
        self.clear_button.setObjectName("clear_button")
        self.division_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("/"))
        self.division_button.setGeometry(QtCore.QRect(270, 100, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.division_button.setFont(font)
        self.division_button.setObjectName("division_button")
        self.dontknow_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("<<"))
        self.dontknow_button.setGeometry(QtCore.QRect(180, 100, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dontknow_button.setFont(font)
        self.dontknow_button.setObjectName("dontknow_button")
        self.seven_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("7"))
        self.seven_button.setGeometry(QtCore.QRect(0, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.seven_button.setFont(font)
        self.seven_button.setObjectName("seven_button")
        self.multiply_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("*"))
        self.multiply_button.setGeometry(QtCore.QRect(270, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.multiply_button.setFont(font)
        self.multiply_button.setObjectName("multiply_button")
        self.nine_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("9"))
        self.nine_button.setGeometry(QtCore.QRect(180, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.nine_button.setFont(font)
        self.nine_button.setObjectName("nine_button")
        self.eight_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("8"))
        self.eight_button.setGeometry(QtCore.QRect(90, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.eight_button.setFont(font)
        self.eight_button.setObjectName("eight_button")
        self.subtract_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("-"))
        self.subtract_button.setGeometry(QtCore.QRect(270, 300, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.subtract_button.setFont(font)
        self.subtract_button.setObjectName("subtract_button")
        self.four_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("4"))
        self.four_button.setGeometry(QtCore.QRect(0, 300, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.four_button.setFont(font)
        self.four_button.setObjectName("four_button")
        self.six_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("6"))
        self.six_button.setGeometry(QtCore.QRect(180, 300, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.six_button.setFont(font)
        self.six_button.setObjectName("six_button")
        self.five_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("5"))
        self.five_button.setGeometry(QtCore.QRect(90, 300, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.five_button.setFont(font)
        self.five_button.setObjectName("five_button")
        self.one_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("1"))
        self.one_button.setGeometry(QtCore.QRect(0, 390, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.one_button.setFont(font)
        self.one_button.setObjectName("one_button")
        self.add_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("+"))
        self.add_button.setGeometry(QtCore.QRect(270, 390, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")
        self.three_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("3"))
        self.three_button.setGeometry(QtCore.QRect(180, 390, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.three_button.setFont(font)
        self.three_button.setObjectName("three_button")
        self.two_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("2"))
        self.two_button.setGeometry(QtCore.QRect(90, 390, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.two_button.setFont(font)
        self.two_button.setObjectName("two_button")
        self.plusminus_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("+/-"))
        self.plusminus_button.setGeometry(QtCore.QRect(0, 480, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusminus_button.setFont(font)
        self.plusminus_button.setObjectName("plusminus_button")
        self.equal_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("="))
        self.equal_button.setGeometry(QtCore.QRect(270, 480, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.equal_button.setFont(font)
        self.equal_button.setObjectName("equal_button")
        self.decimal_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("."))
        self.decimal_button.setGeometry(QtCore.QRect(180, 480, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.decimal_button.setFont(font)
        self.decimal_button.setObjectName("decimal_button")
        self.zero_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("0"))
        self.zero_button.setGeometry(QtCore.QRect(90, 480, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.zero_button.setFont(font)
        self.zero_button.setObjectName("zero_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        
        
        
    def press_it(self, pressed):
       if pressed =="C":
           self.output_label.setText("0")
       
           
       else:
           
           if self.output_label.text()=="0":
               self.output_label.setText("")

               
           
           
           
           
           
           
           
           
           
           
           #concatination.......

           self.output_label.setText(f'{self.output_label.text()}{pressed}')
           
           
       
  


    def retranslateUi(self, MainWindow):

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.output_label.setText(_translate("MainWindow", "0"))
        self.remainder_button.setText(_translate("MainWindow", "%"))
        self.clear_button.setText(_translate("MainWindow", "C"))
        self.division_button.setText(_translate("MainWindow", "/"))
        self.dontknow_button.setText(_translate("MainWindow", "<<"))
        self.seven_button.setText(_translate("MainWindow", "7"))
        self.multiply_button.setText(_translate("MainWindow", "*"))
        self.nine_button.setText(_translate("MainWindow", "9"))
        self.eight_button.setText(_translate("MainWindow", "8"))
        self.subtract_button.setText(_translate("MainWindow", "-"))
        self.four_button.setText(_translate("MainWindow", "4"))
        self.six_button.setText(_translate("MainWindow", "6"))
        self.five_button.setText(_translate("MainWindow", "5"))
        self.one_button.setText(_translate("MainWindow", "1"))
        self.add_button.setText(_translate("MainWindow", "+"))
        self.three_button.setText(_translate("MainWindow", "3"))
        self.two_button.setText(_translate("MainWindow", "2"))
        self.plusminus_button.setText(_translate("MainWindow", "+/-"))
        self.equal_button.setText(_translate("MainWindow", "="))
        self.decimal_button.setText(_translate("MainWindow", "."))
        self.zero_button.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
