# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todo_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 528)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.add_item_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.add_item_pushbutton.setGeometry(QtCore.QRect(60, 130, 131, 28))
        self.add_item_pushbutton.setObjectName("add_item_pushbutton")
        self.add_item_pushbutton.clicked.connect(self.add_it)  # Connect button click to add_it method

        self.delete_item_pushbuuton = QtWidgets.QPushButton(self.centralwidget)
        self.delete_item_pushbuuton.setGeometry(QtCore.QRect(210, 130, 141, 28))
        self.delete_item_pushbuuton.setObjectName("delete_item_pushbuuton")

        self.clear_item_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.clear_item_pushbutton.setGeometry(QtCore.QRect(370, 130, 93, 28))
        self.clear_item_pushbutton.setObjectName("clear_item_pushbutton")

        # Changed from QLineEdit to QListWidget for displaying the list of items
        self.mylist_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.mylist_listWidget.setGeometry(QtCore.QRect(50, 170, 411, 291))
        self.mylist_listWidget.setObjectName("mylist_listWidget")

        self.addItem_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.addItem_lineEdit.setGeometry(QtCore.QRect(50, 50, 401, 61))
        self.addItem_lineEdit.setObjectName("addItem_lineEdit")

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 517, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def add_it(self):
        # Grab the item from the line edit
        item = self.addItem_lineEdit.text()
        if item:
            # Add item to the list widget
            self.mylist_listWidget.addItem(item)
            # Clear the line edit
            self.addItem_lineEdit.setText("")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_item_pushbutton.setText(_translate("MainWindow", "Add Item to a list "))
        self.delete_item_pushbuuton.setText(_translate("MainWindow", "Delete Item to a list"))
        self.clear_item_pushbutton.setText(_translate("MainWindow", "Clear List"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

